version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: ${DOMAIN}
    ports:
      - "${GITLAB_SSH_PORT:-9022}:22"
    volumes:
      - ${GITLAB_DATA_PATH}:/var/opt/gitlab
      - ${GITLAB_LOGS_PATH}:/var/log/gitlab
      - ${GITLAB_CONFIG_PATH}:/etc/gitlab
      # - backup-storage:${GITLAB_BAKUPS:-/backups}
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
      GITLAB_SSH_PORT: ${GITLAB_SSH_PORT:-9022}
      DOMAIN: ${DOMAIN}
      DOMAIN_REGISTRY: ${DOMAIN_REGISTRY}
      DOMAIN_PAGES: ${DOMAIN_PAGES}
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER_NAME: ${SMTP_USER_NAME}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_AUTHENTICATION: ${SMTP_AUTHENTICATION}
      SMTP_ENABLE_STARTTLS_AUTO: ${SMTP_ENABLE_STARTTLS_AUTO}
      SMTP_TLS: ${SMTP_TLS}
      SMTP_OPENSSL_VERIFY_MODE: ${SMTP_OPENSSL_VERIFY_MODE}
      GITLAB_EMAIL: ${GITLAB_EMAIL}
      GITLAB_EMAIL_REPLY_TO: ${GITLAB_EMAIL_REPLY_TO}
      GITLAB_BAKUPS: ${GITLAB_BAKUPS:-/backups}
    configs:
      - source: gitlab-rb-v5
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
      - gitlab_smtp_password
    networks:
      - gitlab
      - default
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.management.gitlab == true
          - node.role == manager
    labels:
      - traefik.enable=true
      # Host settings for GitLab itself
      - traefik.gitlab.frontend.rule=Host:${DOMAIN?Variable DOMAIN not set}
      - traefik.gitlab.port=80
      # Host settings for the registry
      - traefik.registry.frontend.rule=Host:${DOMAIN_REGISTRY?Variable DOMAIN_REGISTRY not set}
      - traefik.registry.port=5100
      # Host settings for GitLab pages. Since I don't have a wildcard certificate, I list every domain on it's own here
      - traefik.pages.frontend.rule=Host:${DOMAIN_PAGES?Variable DOMAIN_PAGES not set},nicolas.${DOMAIN_PAGES?Variable DOMAIN_PAGES not set}
      - traefik.pages.port=5201

  gitlab-runner:
    image: rkcreation/gitlab-runner:latest
    environment:
      - GITLAB_HOST=${DOMAIN}
      - GITLAB_IP=${GITLAB_IP}
      - GITLAB_RUNNER_TOKEN=${GITLAB_RUNNER_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab
    deploy:
      mode: replicated
      replicas: 2

configs:
  gitlab-rb-v5:
    file: ./gitlab.rb
secrets:
  gitlab_root_password:
    external: true
  gitlab_smtp_password:
    external: true

networks:
  default:
    external:
      name: ${NETWORK}
  gitlab:
    driver: overlay
    attachable: true

# volumes:
#   backup-storage:
#     external: true